### ISSUE TITLE
Getteting a error when uploading to FTP

### ISSUE THREAD

**Issue by fellowjamess** [alex-donnan/SyncFTP#8]
I am getting this error: **Failed to connect to SFTP: TypeError: fileObjerts is not iterable**, when uploading to my FTP server. I am using Hostinger as my server provider and followed this [tutorial](https://support.hostinger.com/en/articles/5972689-how-to-connect-to-your-account-using-sftp).

**Comment by fellowjamess** [comment]
Failed to connect: Error: connect->connect: An existing SFTP connection is already defined
    at fmtError (plugin:syncftp:23819:22)
    at SftpClient.connect (plugin:syncftp:24248:17)
    at SFTPClient.connect (plugin:syncftp:27892:27)
    at SyncFTP.uploadFile (plugin:syncftp:28083:38)
    at HTMLDivElement.eval (plugin:syncftp:28053:14)

**Comment by alex-donnan** [comment]
Just to confirm you are successfully able to connect to the SFTP (and not FTP) through Filezilla or other client? If you are unable to connect at all, it is likely a configuration error. I have not run into the existing `SFTP connection is already defined` but that indicates to me that the connection is not connecting and trying to connect during the failing handshake is providing the error, though I cannot be certain of that.

**Comment by fellowjamess** [comment]
It works fine through Filezilla.

**Comment by alex-donnan** [comment]
Is there any way of getting an error log from Hostsinger regarding the SFTP connection failure? To cover all bases are you using a Socks Proxy? The true error of `Failed to connect: Error: connect->connect: An existing SFTP connection is already defined` is typically due to the connection already being connected to an SFTP server at the time it is run. Any other information you can provide would be helpful, as at the current moment it sounds like a configuration issue.

**Comment by fellowjamess** [comment]
It works now for some reason - maybe a restart was enough?

**Comment by alex-donnan** [comment]
I am glad to hear that! Not sure what happened there but perhaps that was it.
